#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 20
#define LARGE_STATE_COUNT 8
#define SYMBOL_COUNT 25
#define ALIAS_COUNT 0
#define TOKEN_COUNT 20
#define EXTERNAL_TOKEN_COUNT 18
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define PRODUCTION_ID_COUNT 1

enum ts_symbol_identifiers {
  anon_sym_DQUOTE = 1,
  sym_line_comment = 2,
  sym_block_comment = 3,
  sym_nested_comment = 4,
  sym_todo_comment = 5,
  sym_identifier = 6,
  sym_builtin_const = 7,
  sym__string_byte = 8,
  sym_escape_sequence = 9,
  sym_bin_prefix = 10,
  sym_bin_literal = 11,
  sym_oct_prefix = 12,
  sym_oct_literal = 13,
  sym_dec_literal = 14,
  sym_hex_prefix = 15,
  sym_hex_literal = 16,
  sym_exponent = 17,
  sym_imag_suffix = 18,
  sym_error_sentinel = 19,
  sym_design_file = 20,
  sym_literal = 21,
  sym_string = 22,
  aux_sym_design_file_repeat1 = 23,
  aux_sym_string_repeat1 = 24,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_DQUOTE] = "\"",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_nested_comment] = "nested_comment",
  [sym_todo_comment] = "todo_comment",
  [sym_identifier] = "identifier",
  [sym_builtin_const] = "builtin_const",
  [sym__string_byte] = "_string_byte",
  [sym_escape_sequence] = "escape_sequence",
  [sym_bin_prefix] = "bin_prefix",
  [sym_bin_literal] = "bin_literal",
  [sym_oct_prefix] = "oct_prefix",
  [sym_oct_literal] = "oct_literal",
  [sym_dec_literal] = "dec_literal",
  [sym_hex_prefix] = "hex_prefix",
  [sym_hex_literal] = "hex_literal",
  [sym_exponent] = "exponent",
  [sym_imag_suffix] = "imag_suffix",
  [sym_error_sentinel] = "error_sentinel",
  [sym_design_file] = "design_file",
  [sym_literal] = "literal",
  [sym_string] = "string",
  [aux_sym_design_file_repeat1] = "design_file_repeat1",
  [aux_sym_string_repeat1] = "string_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_nested_comment] = sym_nested_comment,
  [sym_todo_comment] = sym_todo_comment,
  [sym_identifier] = sym_identifier,
  [sym_builtin_const] = sym_builtin_const,
  [sym__string_byte] = sym__string_byte,
  [sym_escape_sequence] = sym_escape_sequence,
  [sym_bin_prefix] = sym_bin_prefix,
  [sym_bin_literal] = sym_bin_literal,
  [sym_oct_prefix] = sym_oct_prefix,
  [sym_oct_literal] = sym_oct_literal,
  [sym_dec_literal] = sym_dec_literal,
  [sym_hex_prefix] = sym_hex_prefix,
  [sym_hex_literal] = sym_hex_literal,
  [sym_exponent] = sym_exponent,
  [sym_imag_suffix] = sym_imag_suffix,
  [sym_error_sentinel] = sym_error_sentinel,
  [sym_design_file] = sym_design_file,
  [sym_literal] = sym_literal,
  [sym_string] = sym_string,
  [aux_sym_design_file_repeat1] = aux_sym_design_file_repeat1,
  [aux_sym_string_repeat1] = aux_sym_string_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_nested_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_todo_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_builtin_const] = {
    .visible = true,
    .named = true,
  },
  [sym__string_byte] = {
    .visible = false,
    .named = true,
  },
  [sym_escape_sequence] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_bin_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_oct_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_oct_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_dec_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_prefix] = {
    .visible = true,
    .named = true,
  },
  [sym_hex_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_exponent] = {
    .visible = true,
    .named = true,
  },
  [sym_imag_suffix] = {
    .visible = true,
    .named = true,
  },
  [sym_error_sentinel] = {
    .visible = true,
    .named = true,
  },
  [sym_design_file] = {
    .visible = true,
    .named = true,
  },
  [sym_literal] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_design_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_string_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(1);
      if (lookahead == '"') ADVANCE(2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 2:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 0, .external_lex_state = 2},
  [2] = {.lex_state = 0, .external_lex_state = 2},
  [3] = {.lex_state = 0, .external_lex_state = 2},
  [4] = {.lex_state = 0, .external_lex_state = 3},
  [5] = {.lex_state = 0, .external_lex_state = 3},
  [6] = {.lex_state = 0, .external_lex_state = 4},
  [7] = {.lex_state = 0, .external_lex_state = 4},
  [8] = {.lex_state = 0, .external_lex_state = 2},
  [9] = {.lex_state = 0, .external_lex_state = 2},
  [10] = {.lex_state = 0, .external_lex_state = 2},
  [11] = {.lex_state = 0, .external_lex_state = 2},
  [12] = {.lex_state = 0, .external_lex_state = 2},
  [13] = {.lex_state = 0, .external_lex_state = 5},
  [14] = {.lex_state = 0, .external_lex_state = 5},
  [15] = {.lex_state = 0, .external_lex_state = 5},
  [16] = {.lex_state = 0, .external_lex_state = 6},
  [17] = {.lex_state = 0, .external_lex_state = 7},
  [18] = {.lex_state = 0, .external_lex_state = 8},
  [19] = {.lex_state = 0, .external_lex_state = 9},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_nested_comment] = ACTIONS(3),
    [sym_todo_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(1),
    [sym_builtin_const] = ACTIONS(1),
    [sym__string_byte] = ACTIONS(1),
    [sym_escape_sequence] = ACTIONS(1),
    [sym_bin_prefix] = ACTIONS(1),
    [sym_bin_literal] = ACTIONS(1),
    [sym_oct_prefix] = ACTIONS(1),
    [sym_oct_literal] = ACTIONS(1),
    [sym_dec_literal] = ACTIONS(1),
    [sym_hex_prefix] = ACTIONS(1),
    [sym_hex_literal] = ACTIONS(1),
    [sym_exponent] = ACTIONS(1),
    [sym_imag_suffix] = ACTIONS(1),
    [sym_error_sentinel] = ACTIONS(1),
  },
  [1] = {
    [sym_design_file] = STATE(19),
    [sym_literal] = STATE(2),
    [sym_string] = STATE(2),
    [aux_sym_design_file_repeat1] = STATE(2),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_nested_comment] = ACTIONS(3),
    [sym_todo_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(9),
    [sym_builtin_const] = ACTIONS(9),
    [sym_bin_prefix] = ACTIONS(11),
    [sym_oct_prefix] = ACTIONS(13),
    [sym_dec_literal] = ACTIONS(15),
    [sym_hex_prefix] = ACTIONS(17),
  },
  [2] = {
    [sym_literal] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_design_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(19),
    [anon_sym_DQUOTE] = ACTIONS(7),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_nested_comment] = ACTIONS(3),
    [sym_todo_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(21),
    [sym_builtin_const] = ACTIONS(21),
    [sym_bin_prefix] = ACTIONS(11),
    [sym_oct_prefix] = ACTIONS(13),
    [sym_dec_literal] = ACTIONS(15),
    [sym_hex_prefix] = ACTIONS(17),
  },
  [3] = {
    [sym_literal] = STATE(3),
    [sym_string] = STATE(3),
    [aux_sym_design_file_repeat1] = STATE(3),
    [ts_builtin_sym_end] = ACTIONS(23),
    [anon_sym_DQUOTE] = ACTIONS(25),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_nested_comment] = ACTIONS(3),
    [sym_todo_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(28),
    [sym_builtin_const] = ACTIONS(28),
    [sym_bin_prefix] = ACTIONS(31),
    [sym_oct_prefix] = ACTIONS(34),
    [sym_dec_literal] = ACTIONS(37),
    [sym_hex_prefix] = ACTIONS(40),
  },
  [4] = {
    [ts_builtin_sym_end] = ACTIONS(43),
    [anon_sym_DQUOTE] = ACTIONS(43),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_nested_comment] = ACTIONS(3),
    [sym_todo_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(43),
    [sym_builtin_const] = ACTIONS(43),
    [sym_bin_prefix] = ACTIONS(43),
    [sym_oct_prefix] = ACTIONS(43),
    [sym_dec_literal] = ACTIONS(43),
    [sym_hex_prefix] = ACTIONS(43),
    [sym_exponent] = ACTIONS(45),
    [sym_imag_suffix] = ACTIONS(47),
  },
  [5] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_nested_comment] = ACTIONS(3),
    [sym_todo_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(49),
    [sym_builtin_const] = ACTIONS(49),
    [sym_bin_prefix] = ACTIONS(49),
    [sym_oct_prefix] = ACTIONS(49),
    [sym_dec_literal] = ACTIONS(49),
    [sym_hex_prefix] = ACTIONS(49),
    [sym_exponent] = ACTIONS(51),
    [sym_imag_suffix] = ACTIONS(53),
  },
  [6] = {
    [ts_builtin_sym_end] = ACTIONS(49),
    [anon_sym_DQUOTE] = ACTIONS(49),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_nested_comment] = ACTIONS(3),
    [sym_todo_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(49),
    [sym_builtin_const] = ACTIONS(49),
    [sym_bin_prefix] = ACTIONS(49),
    [sym_oct_prefix] = ACTIONS(49),
    [sym_dec_literal] = ACTIONS(49),
    [sym_hex_prefix] = ACTIONS(49),
    [sym_imag_suffix] = ACTIONS(53),
  },
  [7] = {
    [ts_builtin_sym_end] = ACTIONS(55),
    [anon_sym_DQUOTE] = ACTIONS(55),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
    [sym_nested_comment] = ACTIONS(3),
    [sym_todo_comment] = ACTIONS(3),
    [sym_identifier] = ACTIONS(55),
    [sym_builtin_const] = ACTIONS(55),
    [sym_bin_prefix] = ACTIONS(55),
    [sym_oct_prefix] = ACTIONS(55),
    [sym_dec_literal] = ACTIONS(55),
    [sym_hex_prefix] = ACTIONS(55),
    [sym_imag_suffix] = ACTIONS(57),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
    ACTIONS(49), 8,
      sym_identifier,
      sym_builtin_const,
      sym_bin_prefix,
      sym_oct_prefix,
      sym_dec_literal,
      sym_hex_prefix,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
  [17] = 2,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
    ACTIONS(59), 8,
      sym_identifier,
      sym_builtin_const,
      sym_bin_prefix,
      sym_oct_prefix,
      sym_dec_literal,
      sym_hex_prefix,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
  [34] = 2,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
    ACTIONS(55), 8,
      sym_identifier,
      sym_builtin_const,
      sym_bin_prefix,
      sym_oct_prefix,
      sym_dec_literal,
      sym_hex_prefix,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
  [51] = 2,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
    ACTIONS(61), 8,
      sym_identifier,
      sym_builtin_const,
      sym_bin_prefix,
      sym_oct_prefix,
      sym_dec_literal,
      sym_hex_prefix,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
  [68] = 2,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
    ACTIONS(63), 8,
      sym_identifier,
      sym_builtin_const,
      sym_bin_prefix,
      sym_oct_prefix,
      sym_dec_literal,
      sym_hex_prefix,
      ts_builtin_sym_end,
      anon_sym_DQUOTE,
  [85] = 4,
    ACTIONS(65), 1,
      anon_sym_DQUOTE,
    STATE(14), 1,
      aux_sym_string_repeat1,
    ACTIONS(67), 2,
      sym__string_byte,
      sym_escape_sequence,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
  [102] = 4,
    ACTIONS(69), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      aux_sym_string_repeat1,
    ACTIONS(71), 2,
      sym__string_byte,
      sym_escape_sequence,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
  [119] = 4,
    ACTIONS(73), 1,
      anon_sym_DQUOTE,
    STATE(15), 1,
      aux_sym_string_repeat1,
    ACTIONS(75), 2,
      sym__string_byte,
      sym_escape_sequence,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
  [136] = 2,
    ACTIONS(78), 1,
      sym_bin_literal,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
  [146] = 2,
    ACTIONS(78), 1,
      sym_oct_literal,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
  [156] = 2,
    ACTIONS(78), 1,
      sym_hex_literal,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
  [166] = 2,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 4,
      sym_line_comment,
      sym_block_comment,
      sym_nested_comment,
      sym_todo_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(8)] = 0,
  [SMALL_STATE(9)] = 17,
  [SMALL_STATE(10)] = 34,
  [SMALL_STATE(11)] = 51,
  [SMALL_STATE(12)] = 68,
  [SMALL_STATE(13)] = 85,
  [SMALL_STATE(14)] = 102,
  [SMALL_STATE(15)] = 119,
  [SMALL_STATE(16)] = 136,
  [SMALL_STATE(17)] = 146,
  [SMALL_STATE(18)] = 156,
  [SMALL_STATE(19)] = 166,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_design_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_design_file, 1, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_design_file_repeat1, 2, 0, 0),
  [25] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_design_file_repeat1, 2, 0, 0), SHIFT_REPEAT(13),
  [28] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_design_file_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [31] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_design_file_repeat1, 2, 0, 0), SHIFT_REPEAT(16),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_design_file_repeat1, 2, 0, 0), SHIFT_REPEAT(17),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_design_file_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [40] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_design_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 1, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 2, 0, 0),
  [51] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [53] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [55] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 3, 0, 0),
  [57] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 2, 0, 0),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_string, 3, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_literal, 4, 0, 0),
  [65] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [67] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [69] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [71] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0),
  [75] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_string_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [80] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token_line_comment = 0,
  ts_external_token_block_comment = 1,
  ts_external_token_nested_comment = 2,
  ts_external_token_todo_comment = 3,
  ts_external_token_identifier = 4,
  ts_external_token_builtin_const = 5,
  ts_external_token__string_byte = 6,
  ts_external_token_escape_sequence = 7,
  ts_external_token_bin_prefix = 8,
  ts_external_token_bin_literal = 9,
  ts_external_token_oct_prefix = 10,
  ts_external_token_oct_literal = 11,
  ts_external_token_dec_literal = 12,
  ts_external_token_hex_prefix = 13,
  ts_external_token_hex_literal = 14,
  ts_external_token_exponent = 15,
  ts_external_token_imag_suffix = 16,
  ts_external_token_error_sentinel = 17,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token_line_comment] = sym_line_comment,
  [ts_external_token_block_comment] = sym_block_comment,
  [ts_external_token_nested_comment] = sym_nested_comment,
  [ts_external_token_todo_comment] = sym_todo_comment,
  [ts_external_token_identifier] = sym_identifier,
  [ts_external_token_builtin_const] = sym_builtin_const,
  [ts_external_token__string_byte] = sym__string_byte,
  [ts_external_token_escape_sequence] = sym_escape_sequence,
  [ts_external_token_bin_prefix] = sym_bin_prefix,
  [ts_external_token_bin_literal] = sym_bin_literal,
  [ts_external_token_oct_prefix] = sym_oct_prefix,
  [ts_external_token_oct_literal] = sym_oct_literal,
  [ts_external_token_dec_literal] = sym_dec_literal,
  [ts_external_token_hex_prefix] = sym_hex_prefix,
  [ts_external_token_hex_literal] = sym_hex_literal,
  [ts_external_token_exponent] = sym_exponent,
  [ts_external_token_imag_suffix] = sym_imag_suffix,
  [ts_external_token_error_sentinel] = sym_error_sentinel,
};

static const bool ts_external_scanner_states[10][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_builtin_const] = true,
    [ts_external_token__string_byte] = true,
    [ts_external_token_escape_sequence] = true,
    [ts_external_token_bin_prefix] = true,
    [ts_external_token_bin_literal] = true,
    [ts_external_token_oct_prefix] = true,
    [ts_external_token_oct_literal] = true,
    [ts_external_token_dec_literal] = true,
    [ts_external_token_hex_prefix] = true,
    [ts_external_token_hex_literal] = true,
    [ts_external_token_exponent] = true,
    [ts_external_token_imag_suffix] = true,
    [ts_external_token_error_sentinel] = true,
  },
  [2] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_builtin_const] = true,
    [ts_external_token_bin_prefix] = true,
    [ts_external_token_oct_prefix] = true,
    [ts_external_token_dec_literal] = true,
    [ts_external_token_hex_prefix] = true,
  },
  [3] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_builtin_const] = true,
    [ts_external_token_bin_prefix] = true,
    [ts_external_token_oct_prefix] = true,
    [ts_external_token_dec_literal] = true,
    [ts_external_token_hex_prefix] = true,
    [ts_external_token_exponent] = true,
    [ts_external_token_imag_suffix] = true,
  },
  [4] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
    [ts_external_token_identifier] = true,
    [ts_external_token_builtin_const] = true,
    [ts_external_token_bin_prefix] = true,
    [ts_external_token_oct_prefix] = true,
    [ts_external_token_dec_literal] = true,
    [ts_external_token_hex_prefix] = true,
    [ts_external_token_imag_suffix] = true,
  },
  [5] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
    [ts_external_token__string_byte] = true,
    [ts_external_token_escape_sequence] = true,
  },
  [6] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
    [ts_external_token_bin_literal] = true,
  },
  [7] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
    [ts_external_token_oct_literal] = true,
  },
  [8] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
    [ts_external_token_hex_literal] = true,
  },
  [9] = {
    [ts_external_token_line_comment] = true,
    [ts_external_token_block_comment] = true,
    [ts_external_token_nested_comment] = true,
    [ts_external_token_todo_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_alcha_external_scanner_create(void);
void tree_sitter_alcha_external_scanner_destroy(void *);
bool tree_sitter_alcha_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_alcha_external_scanner_serialize(void *, char *);
void tree_sitter_alcha_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_alcha(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_alcha_external_scanner_create,
      tree_sitter_alcha_external_scanner_destroy,
      tree_sitter_alcha_external_scanner_scan,
      tree_sitter_alcha_external_scanner_serialize,
      tree_sitter_alcha_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
